### PR TITLE
ubuntu-image: pin to a working version

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Comment by alfonsosanchezbeato** [comment]
Maybe better for for 3.3 tag to be sure things are fine

**Comment by valentindavid** [comment]
> Maybe better for for 3.3 tag to be sure things are fine

Done.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM

**Comment by valentindavid** [comment]
Fix was merged on ubuntu-image. I am closing this for now. Hoping that the fix works.

**Pull request closed without merging**
